version: '3.5'

networks:
  postgres-network:
    external: true

services:
  bantads-postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - C:/Users/Leonardo/bd:/var/lib/postgresql/data
    networks:
      - postgres-network

  bantads-pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15432:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - C:/Users/Leonardo/bd:/var/lib/postgresql/data
    networks:
      - postgres-network
