export * from './gerente.module';
export * from './services';
export * from './listar-autocadastros';
export * from './gerente-routing.module';
export * from './listar-clientes';
export * from './buscar-cliente';
export * from './modal-filtrar-cliente';
export * from './modal-cliente';
export * from './top-clientes';